name: Publish packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false
        default: No version provided
  push:
    branches:
      - feat/automatic-deploy

jobs:
  setup:
    # TODO: add dependency on all tests passing?
    runs-on: ubuntu-latest

    steps:
      - name: Say version
        run: echo "${{github.event.inputs.version}}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17.1

      - name: Install dependencies
        run: npm install

      - name: Build all packages
        run: npm run build

      - name: Publish packages
        run: echo
