name: Publish packages

on:
  # TODO: for later use
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: Version
  #       required: false
  #       default: No version provided
  push:
    branches:
      - feat/automatic-deploy

  # TODO: add dependency on all tests passing?
  # workflow_run:
  #   workflows: [Tests]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17.1

      - name: Install dependencies
        run: npm install

      - name: Build all packages
        run: npm run build

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/publish
