name: Release packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        default: "No version provided"
  push:
    branches:
      - feat/automatic-deploy

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo Hello world!

      - name: Say version
        run: echo ${{inputs.version}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Say current tag
        run: echo tag=${GITHUB_REF#refs/*/}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17.1
