name: Release packages

on:
  push:
    branches:
      - feat/automatic-deploy

jobs:
  setup:
    steps:
      - name: Say hello
        run: echo Hello world!

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17.1
